OrdererOrgs:
  - Name: Orderer
    Domain: stream.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Sales1
    Domain: sales1.stream.com
    Template: # number of peer
      Count: 2
    Users: # number of user
      Count: 1
  - Name: Customer
    Domain: customer.stream.com
    Template:
      Count: 2
    Users:
      Count: 1